# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  dcapi:
    image: dcapi
    build:
      context: .
      dockerfile: DataCollection/Dockerfile
    ports:
      - 5026:5026

  dpapi:
    image: dpapi
    build:
      context: .
      dockerfile: DataProcessing/Dockerfile
    ports:
      - 5027:5027

##docker run -d --hostname my-rabbit --name some-rabbit -p 15672:15672 -p 5672:5672 rabbitmq:3-management
  rabbitmq:
      image: rabbitmq:3-management
      ports:
        - 15672:15672
        - 5672:5672
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      volumes:
        - rabbitmq:/var/lib/rabbitmq