# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  datainputgatewayapi:
    image: datainputgatewayapi
    build:
      context: .
      dockerfile: src\Gateways\DataInput\Dockerfile
    ports:
      - 5051:5051
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - rabbitmq
  
  mlapi:
    image: mlapi
    build:
      context: .
      dockerfile: src/Services/ML/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  

  dcapi:
    image: dcapi
    build:
      context: .
      dockerfile: src/Services/DataCollection/Dockerfile
    ports:
      - 5026:5026
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - rabbitmq

  dpapi:
    image: dpapi
    build:
      context: .
      dockerfile: src/Services/DataProcessing/Dockerfile
    ports:
      - 5027:5027
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - rabbitmq
      - mlapi

  daapi:
    image: daapi
    build:
      context: .
      dockerfile: src/Services/DataAnalysis/Dockerfile
    ports:
      - 5214:5214
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - rabbitmq

  # monitorgui:
  #   image: monitorgui
  #   build:
  #     context: .
  #     dockerfile: src/GUI/Monitor/Dockerfile